site_name: Estadistica 2


nav:
  - Home: index.md
  - "capitulo 1": capitulo1.ipynb
  - "capitulo 8": capitulo8.ipynb
  - "capitulo 10": capitulo10.ipynb

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true
      
plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      ignore_h1_titles: True

copyright: Copyright &copy; 2023 Cristian Abel
